"""add_user_verification_fields

Revision ID: 9d2cac9ff521
Revises: 6a34de6ddd0e
Create Date: 2026-07-12 15:20:08.192424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d2cac9ff521'
down_revision: Union[str, Sequence[str], None] = '6a34de6ddd0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('verification_code', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('verification_sent_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('verified_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('verified_at')
        batch_op.drop_column('verification_sent_at')
        batch_op.drop_column('verification_code')
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###
